export const token_importer = 'importer';
export const alice = 'alice';
export const bob = 'bob';
export const bod = 'BoD';
export const eb = 'EB';
export const token_exporter = 'exporter';
export const token_issuing = 'issuing_bank';
export const matias = 'matias';
export const ella = 'ella';
export const token_beneficiary = 'beneficiary_bank';
export const reject = 'REJECTED';
export const approve = 'APPROVED'
export const CREATE = 'CREATED';
export const InitialApplicationClass = 'InitialApplication';
export const CustomerClass = 'org.example.loc.Customer'
export const APIURL = "http://192.168.0.102:3000/api/";
//export const mapper =[{'alice':'importer'},{'bob':'exporter'},{'matias':'issuing_bank'},{'ella':'beneficiary_bank'}];